# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
  name: test1
# description will be included in the image's metadata
description: Test of bluebuild, to see if it does what I want, and if atomic distros are for me.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
     # - https://packages.microsoft.com/keys/microsoft.asc
    install:
     # - code
      - kitty
      - obs
      - gparted
      - firefox
    remove:
      - ptyxis
      - konsole
      - distrobox
      - tailscale
      - kwrite
      #- knetattach
      #- sysprof
      #- plasma-systemmonitor
      #- starship
      #- partitionmanager
      #- input-leap
      
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
      - app/io.podman_desktop.PodmanDesktop/x86_64/stable
      remove:
      - app/io.github.dvlv.boxbuddyrs.desktop
      - app/org.fkoehler.KTailctl.desktop
      #- app/org.gnome.World.PikaBackup.desktop
      #- app/org.gnome.World.PikaBackup.Monitor.desktop
      - app/org.kde.haruna.desktop
      - app/org.kde.kontact.desktop
      - app/org.mozilla.Thunderbird.desktop
      - app/org.mozilla.firefox.desktop
      #- app/io.github.input_leap.input-leap/x86_64/stable
      #- app/io.github.pwr_solaar.solaar/x86_64/stable
      
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

